# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "Pabile60"
product_name = "Pabile60"
vendor_id = 0x8065
product_id = 0x4643
manufacturer = "Pabile"
#chip = "rp2040"
#12/12 Error: "The specified chip/board 'pi_pico_w' does not exist in the template repo"
board = "pico_w"

[matrix]
# Input and output pins are mandatory
row_pins = ["PIN_1"]
col_pins = ["PIN_2"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true

[layout]
cols = 1
rows = 1
layers = 1
matrix_map = """
(0,0)
"""
keymap = [
    [
        ["Grave"]
    ]
]

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true

[storage]
# Storage feature is enabled by default
# enabled = false

[ble]
enabled = true
